services:

  logos-blockchain-node-0:
    image: ghcr.io/logos-blockchain/logos-blockchain@sha256:9f1829dea335c56f6ff68ae37ea872ed5313b96b69e8ffe143c02b7217de85fc
    ports:
      - "${PORT:-8080}:18080/tcp"
    volumes:
      - ./scripts:/etc/logos-blockchain/scripts
      - ./kzgrs_test_params:/kzgrs_test_params:z
      - ./node-config.yaml:/etc/logos-blockchain/node-config.yaml:z
      - ./deployment-settings.yaml:/etc/logos-blockchain/deployment-settings.yaml:z
    entrypoint: /etc/logos-blockchain/scripts/run_logos_blockchain_node.sh
