[package]
name = "sequencer_service"
version = "0.1.0"
default-run = "sequencer_service"
edition = "2024"
license = { workspace = true }

[lints]
workspace = true

[dependencies]
sequencer_core = { workspace = true, features = ["testnet"] }
sequencer_executor_actor.workspace = true
sequencer_rpc_server_actor.workspace = true

clap = { workspace = true, features = ["derive", "env"] }
anyhow.workspace = true
env_logger.workspace = true
kameo.workspace = true
kameo_actors.workspace = true
hex.workspace = true
log.workspace = true
metrics-exporter-prometheus.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true

[features]
default = []
# Runs the sequencer in standalone mode without depending on Bedrock and Indexer services.
standalone = ["sequencer_core/mock"]
# Enable mDNS-based local peer discovery for gossip.
mdns = ["sequencer_core/mdns"]
