#!/bin/sh

set -e

export CFG_FILE_PATH="/config.yaml" \
       CFG_SERVER_ADDR="http://cfgsync:4400" \
       CFG_HOST_IP=$(hostname -i) \
       CFG_HOST_IDENTIFIER="validator-$(hostname -i)" \
       LOG_LEVEL="INFO" \
       POL_PROOF_DEV_MODE=true

/usr/bin/logos-blockchain-cfgsync-client

# Download deployment settings generated by cfgsync
curl -sf "${CFG_SERVER_ADDR}/deployment-settings" -o /deployment-settings.yaml

# Set security parameter to 10 to keep integration tests within the 10 minute timeout
sed -i 's/security_param: 30/security_param: 10/' /deployment-settings.yaml

exec /usr/bin/logos-blockchain-node /config.yaml --deployment /deployment-settings.yaml
