//! Golden-vector cross-check (task-1-brief.md's golden-vector methodology).
//!
//! Composes `fee_core`'s public building blocks (`validate_static_block`,
//! `fee_reserve`, `fee_actual_base`, `gas_stor`, `accumulate_gas_used`,
//! `distribute`, `next_base_fee`) into the SPECS.md §Block transition
//! algorithm, exactly as a later task's block-level code will, and checks
//! the result against golden values.
//!
//! The golden values come from three independent sources, none of them this
//! crate's own Rust code:
//! 1. Two are already printed in SPECS.md itself (Annex A "Usage", and the §Overview worked
//!    example) — these are transcription checks.
//! 2. The 8-block scenario and the LCG(42) 10k-block fuzz final line are NOT printed in the spec.
//!    They were generated by transcribing SPECS.md Annex A (the Python reference model) plus Annex
//!    B's `main` driver logic into Python and running it with `python3` (scratch files, not
//!    committed): see task-1-report.md for the transcript. The tuples below are hard-coded from
//!    that run's output.

#![allow(
    clippy::arithmetic_side_effects,
    clippy::integer_division,
    clippy::integer_division_remainder_used,
    reason = "test harness mirrors SPECS.md's block_transition pseudocode directly"
)]

use std::collections::HashMap;

use fee_core::{
    FeeState, FeeTxView, PayerId, accumulate_gas_used, distribute, fee_actual_base, fee_reserve,
    gas_stor, next_base_fee,
    params::{
        BASE_FEE_EXEC_MAX, BASE_FEE_EXEC_MIN, BASE_FEE_STOR_MAX, BASE_FEE_STOR_MIN, D_EXEC, D_STOR,
        MAX_GAS_EXEC, MAX_GAS_STOR, PRIVATE_VERIFY_GAS, TARGET_GAS_EXEC, TARGET_GAS_STOR,
    },
    validate_static_block,
};

const PAYER: PayerId = PayerId([1_u8; 32]);
const PRODUCER: PayerId = PayerId([2_u8; 32]);

/// A block's settlement outcome, mirroring Annex A/B's `BlockReceipt` minus
/// `height` (this crate has no height field; the chain's `block_id` serves
/// as height).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Receipt {
    revenue_base: u128,
    revenue_tip: u128,
    payout: u128,
}

/// Deterministic LCG matching SPECS.md Annex B's `Lcg` (a linear
/// congruential generator: wrapping 64-bit multiply-add, then the high bits
/// modulo `n`). Reused for the fuzz cross-check below and available for any
/// future invariant sweep, per the brief's testing constraints (no new
/// property-testing dependency).
struct Lcg(u64);

impl Lcg {
    const fn below(&mut self, n: u64) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        (self.0 >> 33) % n
    }
}

/// A `FeeTxView` paired with its scripted metered-cycle count.
///
/// `cycles` is TEST SCAFFOLD ONLY (mirroring SPECS.md Annex A/B's
/// `Transaction.mock_cycles`): it is not a `FeeTxView` field — `fee_core`
/// doesn't execute anything, so a real caller gets `cycles` from the
/// execution outcome, not from the transaction. Keeping it independent of
/// `gas_limit` here (rather than always setting `cycles == gas_limit`) is
/// what lets a test express `cycles < gas_limit`, exercising the
/// reserve-vs-actual release path (SPECS.md:132).
#[derive(Debug, Clone, Copy)]
struct ScenarioTx {
    view: FeeTxView,
    cycles: u64,
}

/// Builds a public tx with independent `gas_limit` and `cycles`. The driver
/// scenario/fuzz below always call this with `gas_limit == cycles`,
/// matching Annex B's own `pub_tx(cycles, data, tip, payer)` helper (which
/// sets `mock_cycles == gas_limit`); the usage-example test below is the
/// one place that gives them different values, per SPECS.md Annex A
/// "Usage" (`gas_limit=60_000`, `cycles=50_000`).
const fn pub_tx(gas_limit: u64, cycles: u64, data: u64, tip: u64, payer: PayerId) -> ScenarioTx {
    ScenarioTx {
        view: FeeTxView::Public {
            payer,
            gas_limit,
            data_bytes: data,
            tip,
            max_fee: 1_000_000_000_000_000_000_000_000_000_u128,
        },
        cycles,
    }
}

const fn prv_tx(payer: PayerId) -> ScenarioTx {
    ScenarioTx {
        view: FeeTxView::Private { payer },
        cycles: PRIVATE_VERIFY_GAS,
    }
}

fn tip_of(tx: &FeeTxView) -> u128 {
    match tx {
        FeeTxView::Public { tip, .. } => u128::from(*tip),
        FeeTxView::Private { .. } => 0,
    }
}

/// SPECS.md §Block transition, composed from `fee_core`'s public API.
///
/// Panics (via `unwrap`/`expect`) on any rejection or fault, matching the
/// reference implementations' behavior for the crosscheck driver (which
/// only ever feeds valid blocks).
fn block_transition(
    state: &mut FeeState,
    balances: &mut HashMap<PayerId, u128>,
    txs: &[ScenarioTx],
) -> Receipt {
    let views: Vec<FeeTxView> = txs.iter().map(|tx| tx.view).collect();
    validate_static_block(&views, state).expect("scenario only ever builds valid blocks");

    let mut revenue_base: u128 = 0;
    let mut revenue_tip: u128 = 0;
    let mut gas_used_exec: u64 = 0;
    let mut gas_used_stor: u64 = 0;

    for tx in txs {
        let view = &tx.view;
        let reserve = fee_reserve(view, state);
        let bal = balances.entry(view.payer()).or_insert(0);
        assert!(
            *bal >= reserve,
            "fee debit failed: payer cannot cover reserve"
        );
        *bal -= reserve;

        let cycles = tx.cycles;
        gas_used_exec = accumulate_gas_used(gas_used_exec, cycles, MAX_GAS_EXEC)
            .expect("block exceeds MAX_GAS_EXEC");
        gas_used_stor += gas_stor(view);

        let f_base = fee_actual_base(cycles, view, state);
        let tip = tip_of(view);
        *balances.get_mut(&view.payer()).unwrap() += reserve - (f_base + tip);
        revenue_base += f_base;
        revenue_tip += tip;
    }

    let payout = distribute(state, revenue_base).expect("payout must not exceed escrow");
    *balances.entry(PRODUCER).or_insert(0) += payout + revenue_tip;

    state.base_fee_exec = next_base_fee(
        state.base_fee_exec,
        gas_used_exec,
        TARGET_GAS_EXEC,
        D_EXEC,
        BASE_FEE_EXEC_MIN,
        BASE_FEE_EXEC_MAX,
    );
    state.base_fee_stor = next_base_fee(
        state.base_fee_stor,
        gas_used_stor,
        TARGET_GAS_STOR,
        D_STOR,
        BASE_FEE_STOR_MIN,
        BASE_FEE_STOR_MAX,
    );

    Receipt {
        revenue_base,
        revenue_tip,
        payout,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// SPECS.md Annex A "Usage" example, printed in the spec: from genesis,
    /// one block with a public tx signed at `gas_limit=60_000`,
    /// `data_bytes=200`, `tip=100` but metered at only 50,000 cycles (SPECS
    /// §Fee assessment: `fee_reserve` prices `gas_limit`, `fee_actual_base`
    /// prices the metered `cycles` — they differ here on purpose, so the
    /// unused part of the reservation gets released back to the payer),
    /// plus one private tx.
    ///
    /// `print(r)` in the spec prints
    /// `BlockReceipt(height=1, revenue_base=5472216, revenue_tip=100, payout=109444)`,
    /// and `print(balances)` prints `{1: 999994527684, 2: 109544}`.
    #[test]
    fn usage_example_matches_spec_printed_output() {
        let mut state = FeeState::genesis().unwrap();
        let payer_initial_balance = 1_000_000_000_000_u128;
        let mut balances = HashMap::from([(PAYER, payer_initial_balance), (PRODUCER, 0)]);

        let public = pub_tx(60_000, 50_000, 200, 100, PAYER);
        let private = prv_tx(PAYER);

        let public_reserve = fee_reserve(&public.view, &state);
        // Genesis fees are 8/8: reserve prices gas_limit=60_000 (+ 200 data
        // bytes + the 100 tip); the actual fee below prices the metered
        // 50,000 cycles instead. They must differ for this test to exercise
        // anything (Important review finding round 1): the released
        // reservation is `reserve - actual`, and if `cycles == gas_limit`
        // that release is always zero.
        assert_eq!(public_reserve, 60_000 * 8 + 200 * 8 + 100);
        let public_actual_base = fee_actual_base(50_000, &public.view, &state);
        assert_eq!(public_actual_base, 401_600);
        let public_released = public_reserve - (public_actual_base + 100);
        assert_eq!(public_released, (60_000 - 50_000) * 8);

        // The private tx has no reservation to release: fee_reserve and
        // fee_actual_base are both computed from the same protocol
        // constants, so they're always equal (SPECS §Fee assessment).
        let private_reserve = fee_reserve(&private.view, &state);
        let private_actual_base = fee_actual_base(private.cycles, &private.view, &state);
        assert_eq!(private_reserve, private_actual_base);
        assert_eq!(private_actual_base, 5_070_616);

        let txs = [public, private];
        let receipt = block_transition(&mut state, &mut balances, &txs);

        assert_eq!(
            receipt,
            Receipt {
                revenue_base: 5_472_216,
                revenue_tip: 100,
                payout: 109_444,
            }
        );
        // Payer's net change = -(public fee_total) - (private fee_total);
        // the released part of the public reservation isn't lost, it just
        // never left the payer in the first place.
        let public_fee_total = public_actual_base + 100;
        assert_eq!(
            balances[&PAYER],
            payer_initial_balance - public_fee_total - private_actual_base
        );
        assert_eq!(balances[&PAYER], 999_994_527_684);
        assert_eq!(balances[&PRODUCER], 109_544);
    }

    /// SPECS.md Annex B's `main`: the 8-block scenario immediately followed
    /// by an LCG(42)-driven, 10,000-block fuzz — both on the *same* running
    /// state, exactly as the spec's driver does (the fuzz does not restart
    /// from genesis) — replayed through `fee_core`'s public API.
    ///
    /// The spec does not print this driver's output. Golden values below
    /// were generated independently: SPECS.md Annex A (Python reference
    /// model) plus Annex B's driver logic, transcribed to Python and run
    /// with `python3` (see task-1-report.md for the transcript and
    /// command). Each per-block tuple is `(base_fee_exec, base_fee_stor,
    /// revenue_base, revenue_tip, payout, payout_carry, escrow)` after the
    /// block — the spec's printed columns minus `height` (this crate has
    /// no height field).
    #[test]
    fn cross_check_driver_matches_independently_generated_golden() {
        let mut state = FeeState::genesis().unwrap();
        let mut balances = HashMap::from([(PAYER, 10_u128.pow(30)), (PRODUCER, 10_u128.pow(30))]);

        // Annex B's own `pub_tx(cycles, data, tip, payer)` helper always
        // sets `gas_limit == mock_cycles == cycles`; the scenario below
        // does the same by passing the same value twice (`pub_tx`'s
        // `gas_limit` and `cycles` parameters).
        let scenario: [Vec<ScenarioTx>; 8] = [
            vec![],
            vec![pub_tx(1_000_000, 1_000_000, 40_000, 500, PAYER)],
            vec![pub_tx(5_000_000, 5_000_000, 100_000, 0, PAYER)],
            vec![pub_tx(9_000_000, 9_000_000, 900_000, 2_000, PAYER)],
            vec![pub_tx(10_000_000, 10_000_000, 1_000_000, 0, PAYER)],
            vec![prv_tx(PAYER), prv_tx(PAYER), prv_tx(PAYER), prv_tx(PAYER)],
            vec![
                pub_tx(2_500_000, 2_500_000, 10_000, 1_000, PAYER),
                prv_tx(PAYER),
                prv_tx(PAYER),
            ],
            vec![],
        ];

        // (base_fee_exec, base_fee_stor, revenue_base, revenue_tip, payout, payout_carry, escrow)
        let golden: [(u64, u64, u128, u128, u128, u128, u128); 8] = [
            (8, 8, 0, 0, 0, 0, 0),
            (8, 8, 8_320_000, 500, 166_400, 0, 8_153_600),
            (8, 8, 40_800_000, 0, 982_400, 0, 47_971_200),
            (9, 9, 79_200_000, 2_000, 2_566_400, 0, 124_604_800),
            (10, 10, 99_000_000, 0, 4_546_400, 0, 219_058_400),
            (10, 11, 25_353_080, 0, 5_053_461, 30, 239_358_019),
            (10, 11, 38_234_666, 1_000, 5_818_155, 26, 271_774_530),
            (9, 10, 0, 0, 5_818_155, 22, 265_956_375),
        ];

        for (txs, expected) in scenario.iter().zip(golden) {
            let receipt = block_transition(&mut state, &mut balances, txs);
            let (
                base_fee_exec,
                base_fee_stor,
                revenue_base,
                revenue_tip,
                payout,
                payout_carry,
                escrow,
            ) = expected;
            assert_eq!(state.base_fee_exec, base_fee_exec);
            assert_eq!(state.base_fee_stor, base_fee_stor);
            assert_eq!(receipt.revenue_base, revenue_base);
            assert_eq!(receipt.revenue_tip, revenue_tip);
            assert_eq!(receipt.payout, payout);
            assert_eq!(state.payout_carry, payout_carry);
            assert_eq!(state.escrow, escrow);
        }

        // The fuzz phase continues on the scenario's ending `state`/`balances`
        // (SPECS.md Annex B's `main` runs both phases back to back on one
        // running state; it does not reset to genesis between them).
        let mut rng = Lcg(42);
        for _ in 0..10_000 {
            let mut txs: Vec<ScenarioTx> = Vec::new();
            for _ in 0..rng.below(4) {
                txs.push(prv_tx(PAYER));
            }
            let mut exec_left = MAX_GAS_EXEC - txs.iter().map(|tx| tx.cycles).sum::<u64>();
            let mut stor_left = MAX_GAS_STOR - txs.iter().map(|tx| gas_stor(&tx.view)).sum::<u64>();
            for _ in 0..rng.below(12) {
                let c = 40_000 + rng.below(610_000);
                let d = 1 + rng.below(5_000);
                let t = rng.below(10_000);
                let payer = if rng.below(4) == 0 { PRODUCER } else { PAYER };
                if c <= exec_left && d <= stor_left {
                    // Annex B's driver `pub_tx(cycles, data, tip, payer)`
                    // always sets `gas_limit == cycles` (unlike the
                    // usage-example test above): pass `c` for both.
                    txs.push(pub_tx(c, c, d, t, payer));
                    exec_left -= c;
                    stor_left -= d;
                }
            }
            block_transition(&mut state, &mut balances, &txs);
        }

        assert_eq!(state.base_fee_exec, 8);
        assert_eq!(state.base_fee_stor, 10);
        assert_eq!(state.escrow, 660_097_901);
        assert_eq!(state.payout_carry, 35);
        assert_eq!(state.window.iter().sum::<u128>(), 1_415_910_422);
        assert_eq!(balances[&PAYER], 999_999_999_999_999_999_787_933_683_036);
        assert_eq!(
            balances[&PRODUCER],
            1_000_000_000_000_000_000_211_406_219_063
        );
    }
}
