[package]
name = "sequencer_genesis"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lints]
workspace = true

[dependencies]
lee.workspace = true
lee_core.workspace = true
common.workspace = true
programs.workspace = true
system_accounts.workspace = true
testnet_initial_state.workspace = true
authenticated_transfer_core.workspace = true
bridge_core.workspace = true
fee_core.workspace = true
cross_zone.workspace = true
cross_zone_inbox_core.workspace = true
sequencer_stake_core.workspace = true

serde.workspace = true
hex.workspace = true
log.workspace = true
