use serde::{Deserialize, Serialize};

pub type NullifierSecretKey = [u8; 32];

/// Payload generated by the user when publishing an anonymous post.
/// This payload will be sent to the Logos network (Basecamp app).
#[derive(Serialize, Deserialize, Clone)]
pub struct PostPayload {
    pub message: Vec<u8>,
    pub tracing_tag: [u8; 32],
    pub x_index: u8, 
    pub encrypted_shares: Vec<EncryptedSharePerPost>,
}

/// Tier 1 secret fragment encrypted specifically for one moderator.
#[derive(Serialize, Deserialize, Clone)]
pub struct EncryptedSharePerPost {
    pub moderator_pubkey: [u8; 32], 
    pub ephemeral_pk: [u8; 32], 
    pub ciphertext: Vec<u8>, 
}

/// Certificate generated by moderators when they issue a "Strike".
#[derive(Serialize, Deserialize, Clone)]
pub struct ModerationCertificate {
    pub tracing_tag: [u8; 32],
    pub decrypted_share: Vec<u8>, 
    pub moderator_signature: Vec<u8>, 
    pub moderator_pubkey: Vec<u8>,
}