// Generated by `tools/image_id_pin` (run through `just build-artifacts`) from
// `artifacts/lez/programs/authenticated_transfer.bin`.

#[expect(clippy::unreadable_literal, reason = "generated image id from risc0")]
pub const AUTHENTICATED_TRANSFER_IMAGE_ID: [u32; 8] = [
    2476711475, 1224982153, 3117873563, 2523167880, 1035873034, 1388799342, 361406495, 3850721221,
];
