// GENERATED by `tools/image_id_pin` (run through `just build-artifacts`) from
// `artifacts/lez/programs/authenticated_transfer.bin` — do not edit by hand.
//
// `include!`d by guests that chain calls into `authenticated_transfer`, never
// by `authenticated_transfer` itself: its own ELF must not depend on this
// value, or refreshing it would move the very image id it pins.
#[expect(
    clippy::unreadable_literal,
    reason = "generated image id from risc0, a cryptographic hash as a u32 array"
)]
pub const AUTHENTICATED_TRANSFER_IMAGE_ID: [u32; 8] = [2476711475, 1224982153, 3117873563, 2523167880, 1035873034, 1388799342, 361406495, 3850721221];
