use common::block::Block;
use futures::{StreamExt as _, future::OptionFuture};
use kameo::{
    Actor,
    actor::{ActorRef, WeakActorRef},
    mailbox::{MailboxReceiver, Signal},
    message::{Context, Message},
};
use kameo_actors::broker::Broker;
use log::warn;
use logos_blockchain_common_http_client::BasicAuthCredentials;
use logos_blockchain_core::mantle::NoteId;
use logos_blockchain_zone_sdk::{
    CommonHttpClient,
    adapter::{Node as _, NodeHttpClient},
    node_types::Inscription,
    sequencer::{ChannelUpdateTx, InscriptionInfo, PendingTx},
};
use tokio::select;
use url::Url;

#[cfg(feature = "test-utils")]
use crate::protocol::PublishRawInscription;
use crate::{
    BedrockActorTrait, Result,
    error::Error,
    protocol::{
        AccreditedKeys, BoxStream, ChangeChannelConfig, ChannelEvent, ChannelId,
        CheckChannelExists, CheckIsOurTurn, CreateChannel, GetAccreditedKeys,
        GetChannelTipMessageId, GetChannelTipSlot, InitializeChannelPublisher, MsgId, PublishBlock,
        PublishOutcome, ReadChannel, Slot, ZoneMessage,
    },
};

mod publisher;
#[cfg(test)]
mod tests;

/// Bedrock Actor responsible for interacting with the Bedrock node and managing channel events.
///
/// This actor is expected to be used together with [`sharding_pool_actor`]. However it can be used
/// on its own but make sure to provide the correct `channel_id` in every message. Passing
/// unexpected `channel_id` will lead to a panic.
///
/// To be able to submit channel updates, you must first submit an [`InitializeChannelPublisher`]
/// message, otherwise [`Error::ChannelPublisherIsNotInitialized`] will be returned.
///
/// [`BedrockActor`] will post [`ChannelEvent`]s to the provided broker using the following topics:
/// - `channel/<channel_id>/update`: for [`ChannelEvent::Update`]
/// - `channel/<channel_id>/turn`: for [`ChannelEvent::Turn`]
pub struct BedrockActor {
    channel_id: ChannelId,
    node: NodeHttpClient,
    /// [`Some`] after [`InitializeChannelPublisher`] has been handled.
    publisher: Option<publisher::Publisher>,
    broker_ref: ActorRef<Broker<ChannelEvent>>,
}

impl BedrockActor {
    #[must_use]
    pub fn new(
        node_url: Url,
        basic_auth: Option<BasicAuthCredentials>,
        channel_id: ChannelId,
        broker_ref: ActorRef<Broker<ChannelEvent>>,
    ) -> Self {
        let node = NodeHttpClient::new(CommonHttpClient::new(basic_auth), node_url);

        Self {
            channel_id,
            node,
            publisher: None,
            broker_ref,
        }
    }

    fn assert_channel_id(&self, channel_id: ChannelId) {
        assert_eq!(self.channel_id, channel_id, "Channel ID mismatch");
    }

    fn publisher(&mut self) -> Result<&mut publisher::Publisher> {
        self.publisher
            .as_mut()
            .ok_or(Error::ChannelPublisherIsNotInitialized)
    }
}

impl BedrockActorTrait for BedrockActor {}

impl Actor for BedrockActor {
    type Args = Self;
    type Error = Error;

    async fn on_start(args: Self::Args, _actor_ref: ActorRef<Self>) -> Result<Self> {
        Ok(args)
    }

    async fn next(
        &mut self,
        _actor_ref: WeakActorRef<Self>,
        mailbox_rx: &mut MailboxReceiver<Self>,
    ) -> Result<Option<Signal<Self>>> {
        #[expect(
            clippy::integer_division_remainder_used,
            reason = "Generated by select! macro, can't be easily rewritten to avoid this lint"
        )]
        loop {
            select! {
                Some(res) = OptionFuture::from(self.publisher.as_mut().map(|writer| writer.step(
                    self.channel_id,
                    &self.broker_ref,
                ))) => {
                    res?;
                }
                signal = mailbox_rx.recv() => {
                    return Ok(signal)
                }
            }
        }
    }
}

impl Message<InitializeChannelPublisher> for BedrockActor {
    type Reply = Result<bool>;

    async fn handle(
        &mut self,
        InitializeChannelPublisher {
            channel_id,
            bedrock_signing_key,
            funding_pk,
            priority_fee_percent,
            initial_checkpoint,
            resubmit_interval,
        }: InitializeChannelPublisher,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.assert_channel_id(channel_id);

        if self.publisher.is_some() {
            return Ok(false);
        }

        self.publisher = Some(
            publisher::Publisher::new(
                self.node.clone(),
                self.channel_id,
                bedrock_signing_key,
                funding_pk,
                priority_fee_percent,
                initial_checkpoint,
                resubmit_interval,
            )
            .await?,
        );
        Ok(true)
    }
}

impl Message<CreateChannel> for BedrockActor {
    type Reply = Result<PublishOutcome>;

    async fn handle(
        &mut self,
        CreateChannel {
            channel_id,
            genesis,
            keys,
            channel_params,
        }: CreateChannel,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.assert_channel_id(channel_id);

        self.publisher()?
            .create_channel(channel_id, genesis, keys, channel_params)
            .await
    }
}

impl Message<PublishBlock> for BedrockActor {
    type Reply = Result<PublishOutcome>;

    async fn handle(
        &mut self,
        PublishBlock {
            channel_id,
            block,
            withdrawals,
            parent,
        }: PublishBlock,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.assert_channel_id(channel_id);

        self.publisher()?
            .publish_block(channel_id, block, withdrawals, parent)
            .await
    }
}

impl Message<ChangeChannelConfig> for BedrockActor {
    type Reply = Result<()>;

    async fn handle(
        &mut self,
        ChangeChannelConfig {
            channel_id,
            new_keys,
            posting_timeframe,
            posting_timeout,
            configuration_threshold,
            transfer_threshold,
        }: ChangeChannelConfig,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.assert_channel_id(channel_id);

        self.publisher()?
            .change_channel_config(
                new_keys,
                posting_timeframe,
                posting_timeout,
                configuration_threshold,
                transfer_threshold,
            )
            .await
    }
}

impl Message<CheckChannelExists> for BedrockActor {
    type Reply = Result<bool>;

    async fn handle(
        &mut self,
        _msg: CheckChannelExists,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        Ok(self
            .node
            .channel_state(self.channel_id)
            .await
            .map_err(|err| Error::NodeRequestFailed(err.into()))?
            .is_some())
    }
}

impl Message<CheckIsOurTurn> for BedrockActor {
    type Reply = Result<bool>;

    async fn handle(
        &mut self,
        CheckIsOurTurn { channel_id }: CheckIsOurTurn,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.assert_channel_id(channel_id);

        Ok(self.publisher()?.check_is_our_turn())
    }
}

impl Message<GetAccreditedKeys> for BedrockActor {
    type Reply = Result<Option<AccreditedKeys>>;

    async fn handle(
        &mut self,
        GetAccreditedKeys { channel_id }: GetAccreditedKeys,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.assert_channel_id(channel_id);

        Ok(self
            .node
            .channel_state(self.channel_id)
            .await
            .map_err(|err| Error::NodeRequestFailed(err.into()))?
            .map(|state| AccreditedKeys {
                keys: state.accredited_keys.to_vec(),
                config_tip: state.config_tip_hash,
                tip_sequencer: state.tip_sequencer,
                tip_slot: state.tip_slot,
            }))
    }
}

impl Message<GetChannelTipSlot> for BedrockActor {
    type Reply = Result<Option<Slot>>;

    async fn handle(
        &mut self,
        GetChannelTipSlot { channel_id }: GetChannelTipSlot,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.assert_channel_id(channel_id);

        Ok(self
            .node
            .channel_state(self.channel_id)
            .await
            .map_err(|err| Error::NodeRequestFailed(err.into()))?
            .map(|state| state.tip_slot))
    }
}

impl Message<GetChannelTipMessageId> for BedrockActor {
    type Reply = Result<Option<MsgId>>;

    async fn handle(
        &mut self,
        GetChannelTipMessageId { channel_id }: GetChannelTipMessageId,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.assert_channel_id(channel_id);

        Ok(self
            .node
            .channel_state(self.channel_id)
            .await
            .map_err(|err| Error::NodeRequestFailed(err.into()))?
            .map(|state| state.tip_message))
    }
}

impl Message<ReadChannel> for BedrockActor {
    type Reply = Result<BoxStream<(ZoneMessage, Slot)>>;

    async fn handle(
        &mut self,
        ReadChannel { channel_id, after }: ReadChannel,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        const BATCH_SIZE: Slot = Slot::new(100);

        self.assert_channel_id(channel_id);

        let lib_slot = self
            .node
            .consensus_info()
            .await
            .map_err(|err| Error::NodeRequestFailed(err.into()))?
            .cryptarchia_info
            .lib_slot;
        let start_slot = after.map_or_else(Slot::genesis, |s| s.strict_add(1.into()));

        let node = self.node.clone();
        let stream = futures::stream::unfold(start_slot, move |current_slot| {
            let node = node.clone();
            async move {
                if current_slot > lib_slot {
                    return None;
                }

                let end_slot = (Slot::from(
                    current_slot
                        .into_inner()
                        .saturating_add(BATCH_SIZE.into_inner())
                        .checked_sub(1)
                        .expect("slot shouldn't overflow"),
                ))
                .min(lib_slot);

                match node
                    .zone_messages_in_blocks(current_slot, end_slot, channel_id)
                    .await
                {
                    Ok(messages) => Some((messages, end_slot.strict_add(1.into()))),
                    Err(e) => {
                        log::warn!(
                            "Failed to fetch zone messages from blocks {current_slot:?}..={end_slot:?}: {e}",
                        );
                        None
                    }
                }
            }
        })
        .flatten();

        Ok(Box::pin(stream))
    }
}

#[cfg(feature = "test-utils")]
impl Message<PublishRawInscription> for BedrockActor {
    type Reply = Result<PublishOutcome>;

    async fn handle(
        &mut self,
        PublishRawInscription { channel_id, data }: PublishRawInscription,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.assert_channel_id(channel_id);

        self.publisher()?.publish_raw_inscription(data).await
    }
}

/// Every block a channel tx carries, in op order.
///
/// A config op is on the config lineage, not this one, so it is skipped.
fn channel_blocks(tx: &ChannelUpdateTx, channel_id: ChannelId) -> Vec<Block> {
    let entry = |inscription: &InscriptionInfo| {
        if <Inscription as AsRef<[u8]>>::as_ref(&inscription.payload).is_empty() {
            None
        } else {
            block_from_inscription(inscription)
        }
    };
    match tx {
        ChannelUpdateTx::Inscription(info) => entry(info).into_iter().collect(),
        ChannelUpdateTx::AtomicWithdraw(bundle) => entry(&bundle.inscription).into_iter().collect(),
        // A config-only tx carries no payload to apply.
        ChannelUpdateTx::Config(_) => Vec::new(),
        ChannelUpdateTx::Custom(signed_tx) => {
            logos_blockchain_zone_sdk::sequencer::channel_inscriptions(signed_tx, channel_id)
                .iter()
                .filter_map(entry)
                .collect()
        }
    }
}

/// Deserialize an inscription payload into `(this_msg, Block)`. Bad payloads are
/// logged and skipped.
fn block_from_inscription(inscription: &InscriptionInfo) -> Option<Block> {
    borsh::from_slice::<Block>(&inscription.payload)
        .inspect_err(|err| {
            warn!("Failed to deserialize block from inscription: {err:?}");
        })
        .ok()
}

/// Channel notes the withdraws bundled with a published tx release; empty for a
/// plain inscription. See [`PublishOutcome::released_notes`].
fn released_notes(tx: &PendingTx) -> Vec<NoteId> {
    match tx {
        PendingTx::Inscription(_) => Vec::new(),
        PendingTx::AtomicWithdraw(bundle) => bundle
            .withdraws
            .iter()
            .flat_map(|withdraw| withdraw.op.inputs.iter().copied())
            .collect(),
    }
}
