use nssa::{
    V03State,
    public_transaction::{Message, PublicTransaction, WitnessSet},
    program::Program,
};
use nssa_core::account::AccountId;
use lez_sdk::routing::GeneralCallInstruction;
use risc0_zkvm::serde::to_vec;

// Include the "methods.rs" file generated by build.rs
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

/// Helper to create initial call instructions from the user
fn create_user_instruction(function_id: &str, args_u32: Vec<u32>) -> GeneralCallInstruction {
    GeneralCallInstruction {
        route: None, // User DOES NOT have a return route
        function_id: function_id.to_string(),
        args: args_u32, 
    }
}

/// Helper to set up the initial state (registering accounts and programs via Genesis)
fn setup_test_state() -> (V03State, AccountId) {
    // 1. Create a dummy account for the user
    let user_account_id = AccountId::new([99; 32]);

    // 2. Load Program A and B from the ELF file
    let prog_a = Program::new(DEMO_CALL_A_ELF.to_vec()).unwrap();
    let prog_b = Program::new(DEMO_CALL_B_ELF.to_vec()).unwrap();

    // 3. Insert the account into Genesis (Format: Account ID, Initial Balance)
    // We give this test user an initial balance of 1,000,000 tokens
    let genesis_accounts = [(user_account_id, 1_000_000_u128)];

    // 4. Initialize V03State
    // Argument 1: Public accounts
    // Argument 2: Private state (Commitment, Nullifier) -> we provide an empty array
    // Argument 3: Block index/timestamp -> 0
    let mut state = V03State::new_with_genesis_accounts(
        &genesis_accounts, 
        vec![], 
        0
    );

    // 5. Register the programs in the state (use standard insert_program)
    state.force_insert_program(DEMO_CALL_A_ID, prog_a);
    state.force_insert_program(DEMO_CALL_B_ID, prog_b);

    (state, user_account_id)
}

#[test]
fn test_multi_hop_positive_chain() {
    println!("--- Starting Multi-Hop Positive Test (A -> B -> A) ---");
    let (mut state, _user_account_id) = setup_test_state();

    // User calls the #[public] function "start_chain" with arguments (user_id: 1, amount: 500)
    let user_args = (1u64, 500u64, DEMO_CALL_B_ID);
    let args_u32 = to_vec(&user_args).unwrap();
    let instruction_data = create_user_instruction("start_chain", args_u32);

    // Create a public transaction message
    let message = Message::try_new(
        DEMO_CALL_A_ID, 
        vec![], 
        vec![], 
        instruction_data
    ).unwrap();
    
    let witness_set = WitnessSet::for_message(&message, &[]);
    let tx = PublicTransaction::new(message, witness_set);

    // EXECUTION: The Sequencer will run A, receive a Capability Ticket, 
    // execute B, then B returns control to A, A validates the ticket, and completes.
    let result = state.transition_from_public_transaction(&tx, 1, 0);

    // TESTING: Transaction must SUCCEED (Ok)
    assert!(
        result.is_ok(), 
        "Positive scenario failed! The Sequencer rejected the A->B->A execution. Error: {:?}", 
        result.err()
    );
    println!("✅ Positive scenario succeeded: state was successfully committed!");
}

#[test]
fn test_negative_direct_call() {
    println!("--- Starting Negative Test (Direct Access Rejected) ---");
    let (mut state, _user_account_id) = setup_test_state();

    // Malicious user tries to call the #[internal] function "continue_chain" directly!
    // Arguments: (user_id: 1, initial_balance: 1000) and b_success: true
    let fake_local_state = (1u64, 1000u64);
    let fake_success = true;
    let fake_args = (fake_local_state, fake_success);
    let args_u32 = to_vec(&fake_args).unwrap();
    
    // User has no ticket, so route: None
    let instruction_data = create_user_instruction("continue_chain", args_u32);

    let message = Message::try_new(
        DEMO_CALL_A_ID, 
        vec![], 
        vec![], 
        instruction_data
    ).unwrap();
    
    let witness_set = WitnessSet::for_message(&message, &[]);
    let tx = PublicTransaction::new(message, witness_set);

    // EXECUTION
    let result = state.transition_from_public_transaction(&tx, 1, 0);

    // TESTING: Transaction must FAIL (Err) because the ticket is not found in active_tickets
    assert!(
        result.is_err(), 
        "Negative scenario failed! Security gap: the Sequencer allowed the user to call an internal function directly!"
    );
    
    println!("❌ Negative scenario successfully blocked: the Sequencer rejected the transaction because no valid Capability Ticket was present.");
}

#[test]
fn test_replay_and_forged_ticket() {
    println!("--- Starting Negative Test (Replay Attack & Forged Ticket) ---");
    let (mut state, _user_account_id) = setup_test_state();

    // 1. Assume the attacker tries to create a forged ticket (or use an expired ticket)
    let forged_ticket_hash = [8u8; 32]; 
    let fake_local_state = (1u64, 1000u64);
    let fake_success = true;
    let fake_args = (fake_local_state, fake_success);
    let args_u32 = to_vec(&fake_args).unwrap();

    // 2. The attacker constructs a forged ReturnRoute
    let forged_route = lez_sdk::routing::ReturnRoute {
        caller_program_id: DEMO_CALL_A_ID,
        continuation_id: "continue_chain".to_string(),
        ticket_hash: forged_ticket_hash,
        context_payload: to_vec(&fake_local_state).unwrap(),
    };

    // 3. Insert this forged route as if it were called internally
    let instruction_data = GeneralCallInstruction {
        route: Some(forged_route),
        function_id: "continue_chain".to_string(),
        args: args_u32,
    };

    let message = Message::try_new(
        DEMO_CALL_A_ID, 
        vec![], 
        vec![], 
        instruction_data 
    ).unwrap();
    
    let witness_set = WitnessSet::for_message(&message, &[]);
    let tx = PublicTransaction::new(message, witness_set);

    // EXECUTION
    let result = state.transition_from_public_transaction(&tx, 1, 0);

    // TESTING: The transaction must FAIL because the ticket is invalid / not present in active_tickets
    assert!(
        result.is_err(), 
        "Replay attack scenario failed! Security gap: the Sequencer accepted a forged or expired ticket!"
    );
    
    println!("❌ Replay/Forged scenario successfully blocked: the Sequencer detected an invalid ticket.");
}