use std::net::SocketAddr;

use anyhow::{Context as _, Result};
use futures::never::Never;
use kameo::actor::Spawn as _;
use kameo_actors::scheduler::{Scheduler, SetInterval};
use log::info;
pub use sequencer_core::config::*;
use sequencer_core::load_or_create_signing_key;
use sequencer_executor_actor::ExecutorActor;
use sequencer_rpc_server_actor::RpcServerActor;
use tokio::select;

use crate::actor_handle::ActorHandle;

mod actor_handle;

#[cfg(not(feature = "standalone"))]
type BlockPublisher = sequencer_core::block_publisher::ZoneSdkPublisher;

#[cfg(feature = "standalone")]
type BlockPublisher = sequencer_core::mock::MockBlockPublisher;

/// Handle to manage the sequencer and its tasks.
///
/// Implements `Drop` to ensure all actors are killed when dropped.
pub struct SequencerHandle {
    // NOTE: Order of fields matters as it affects drop order.
    scheduler: ActorHandle<Scheduler>,
    rpc_server: ActorHandle<RpcServerActor>,
    executor: ActorHandle<ExecutorActor<BlockPublisher>>,
    addr: SocketAddr,
    /// Held for its lifetime: dropping it stops the gossip drive task.
    /// `None` when gossip is unconfigured.
    gossip: Option<sequencer_core::gossip::GossipNetwork>,
}

impl SequencerHandle {
    const fn new(
        scheduler: ActorHandle<Scheduler>,
        rpc_server: ActorHandle<RpcServerActor>,
        executor: ActorHandle<ExecutorActor<BlockPublisher>>,
        addr: SocketAddr,
        gossip: Option<sequencer_core::gossip::GossipNetwork>,
    ) -> Self {
        Self {
            scheduler,
            rpc_server,
            executor,
            addr,
            gossip,
        }
    }

    /// Stops the sequencer and waits for every part of it to be gone.
    /// executor itself.
    pub async fn shutdown(self) {
        let Self {
            scheduler,
            rpc_server,
            executor,
            addr: _,
            gossip: _,
        } = self;

        // NOTE: Order of shutdown matters. Make sure it follows the order of fields in the struct.
        scheduler.shutdown().await;
        rpc_server.shutdown().await;
        executor.shutdown().await;
    }

    /// Wait for any of the sequencer tasks to fail and return the error.
    #[expect(
        clippy::integer_division_remainder_used,
        reason = "Generated by select! macro, can't be easily rewritten to avoid this lint"
    )]
    pub async fn failed(&self) -> Result<Never> {
        let Self {
            executor,
            rpc_server,
            scheduler,
            addr: _,
            gossip: _,
        } = self;

        select! {
            Err(err) = executor.failed() => {
                Err(err)
            }
            Err(err) = rpc_server.failed() => {
                Err(err)
            }
            Err(err) = scheduler.failed() => {
                Err(err)
            }
        }
    }

    /// Check if all Sequencer tasks are still running.
    ///
    /// Return `false` if any of the tasks has failed and `true` otherwise.
    /// Error of the failed task can be retrieved by awaiting on [`Self::failed()`].
    #[must_use]
    pub fn is_healthy(&self) -> bool {
        let Self {
            executor,
            rpc_server,
            scheduler,
            addr: _,
            gossip: _,
        } = self;

        executor.is_healthy() && rpc_server.is_healthy() && scheduler.is_healthy()
    }

    #[must_use]
    pub const fn addr(&self) -> SocketAddr {
        self.addr
    }

    /// Multiaddrs (with the `/p2p/` peer id suffix) other nodes can use as
    /// gossip `bootstrap_peers`. `None` when gossip is unconfigured.
    #[must_use]
    pub fn gossip_bootstrap_addrs(&self) -> Option<Vec<sequencer_core::gossip::Multiaddr>> {
        self.gossip
            .as_ref()
            .map(sequencer_core::gossip::GossipNetwork::bootstrap_addrs)
    }
}

pub async fn run(config: SequencerConfig, listen_addr: SocketAddr) -> Result<SequencerHandle> {
    let block_timeout = config.block_create_timeout;
    let max_block_size = config.max_block_size;

    // Captured before `config` moves into the executor; gossip needs them after.
    let gossip_config = config.gossip.clone();
    let bedrock_config = config.bedrock_config.clone();
    let sequencer_home = config.home.clone();

    let executor = ExecutorActor::new(config).await;
    let mempool_handle = executor.mempool_handle();
    let executor_ref = ExecutorActor::spawn(executor);
    info!("Executor Actor spawned");

    // Gossip is constructed only when configured; a `None` config means no
    // sockets and no tasks. Startup failure here is a hard error
    // (misconfiguration); after startup, gossip never halts the node.
    let gossip_network = match gossip_config {
        None => None,
        Some(gossip_config) => {
            // The node's L1 bedrock signing key is deliberately reused as the
            // libp2p identity; `GossipNetwork::start` derives the keypair.
            let signing_key =
                load_or_create_signing_key(&sequencer_home.join("bedrock_signing_key"))?;
            let channel_id = *bedrock_config.channel_id.as_ref();
            let network = sequencer_core::gossip::GossipNetwork::start(
                gossip_config,
                channel_id,
                signing_key,
                mempool_handle,
                max_block_size.as_u64(),
            )
            .await
            .context("Failed to start sequencer gossip network")?;
            info!("Gossip network started as {}", network.local_peer_id());
            Some(network)
        }
    };
    let tx_publisher = gossip_network
        .as_ref()
        .map(sequencer_core::gossip::GossipNetwork::tx_publisher);

    let rpc_server = RpcServerActor::new(
        executor_ref.clone(),
        listen_addr,
        max_block_size,
        tx_publisher,
    )
    .await?;
    let addr = rpc_server.addr();
    let rpc_server_ref = RpcServerActor::spawn(rpc_server);
    info!("RPC Server Actor spawned");

    let scheduler_ref = Scheduler::spawn(Scheduler::new());
    scheduler_ref
        .tell(
            SetInterval::new(
                executor_ref.downgrade(),
                block_timeout,
                sequencer_executor_actor::protocol::ProduceBlock,
            )
            .start_delay(block_timeout)
            .set_missed_tick_behaviour(tokio::time::MissedTickBehavior::Delay),
        )
        .await?;
    info!("Block production scheduler started");

    Ok(SequencerHandle::new(
        ActorHandle::new(scheduler_ref),
        ActorHandle::new(rpc_server_ref),
        ActorHandle::new(executor_ref),
        addr,
        gossip_network,
    ))
}
