use std::{
    net::{IpAddr, SocketAddr},
    path::{Path, PathBuf},
};

use anyhow::{Context as _, Result};
use clap::{Parser, Subcommand};
use log::error;
use metrics_exporter_prometheus::{Matcher, PrometheusBuilder};
use sequencer_stake_core::SequencerKey;
use tokio::signal::unix::{SignalKind, signal};
use tokio_util::sync::CancellationToken;
use wallet::cli::CliAccountMention;

mod operator;

#[derive(Debug, Parser)]
#[clap(version)]
struct Args {
    #[clap(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Creates a home with its config and Bedrock funding public key.
    Setup {
        home: PathBuf,
        /// Config to copy into the home.
        #[clap(long)]
        config: PathBuf,
        /// Public key, in hex, of a funded key in the Bedrock node's wallet; it pays the
        /// node's inscriptions.
        #[clap(long)]
        funding_public_key: String,
        /// Keeps the config's `genesis`, so `start` creates the channel if it does not exist.
        #[clap(long)]
        create_channel: bool,
    },
    /// Runs the sequencer out of a home, following the channel.
    Start {
        home: PathBuf,
        #[clap(short, long, default_value = "3040")]
        port: u16,
        /// Interface the RPC server binds to. The RPC has no caller auth, so only widen it
        /// behind a firewall.
        #[clap(long, default_value = "127.0.0.1")]
        listen_address: IpAddr,
        /// Overrides the config's `metrics_address`.
        #[clap(long)]
        metrics_address: Option<SocketAddr>,
    },
    /// Stakes a channel signing key, through the wallet's sequencer.
    Stake {
        /// Channel signing public key to stake, in hex; `setup` prints it.
        #[clap(long, value_parser = operator::parse_sequencer_key)]
        sequencer_key: SequencerKey,
        /// Wallet account paying the stake, as `Public/<id>` or a label.
        #[clap(long)]
        from: CliAccountMention,
        /// Defaults to the minimum stake.
        #[clap(long)]
        amount: Option<u128>,
        /// Defaults to `$LEE_WALLET_HOME_DIR`, else `~/.lee/wallet`.
        #[clap(long)]
        wallet_home: Option<PathBuf>,
    },
    /// Requests the release of a channel signing key's stake, through the wallet's sequencer.
    Unstake {
        /// Channel signing public key whose stake to release, in hex.
        #[clap(long, value_parser = operator::parse_sequencer_key)]
        sequencer_key: SequencerKey,
        /// Account receiving the release, as `Public/<id>` or a label.
        #[clap(long)]
        destination: CliAccountMention,
        /// Defaults to the whole stake.
        #[clap(long)]
        amount: Option<u128>,
        /// Defaults to `$LEE_WALLET_HOME_DIR`, else `~/.lee/wallet`.
        #[clap(long)]
        wallet_home: Option<PathBuf>,
    },
}

#[tokio::main]
async fn main() -> Result<()> {
    env_logger::init();

    match Args::parse().command {
        Command::Setup {
            home,
            config,
            funding_public_key,
            create_channel,
        } => operator::setup(&home, &config, &funding_public_key, create_channel),
        Command::Start {
            home,
            port,
            listen_address,
            metrics_address,
        } => {
            start(
                &home,
                SocketAddr::new(listen_address, port),
                metrics_address,
            )
            .await
        }
        Command::Stake {
            sequencer_key,
            from,
            amount,
            wallet_home,
        } => operator::stake(wallet_home, sequencer_key, from, amount).await,
        Command::Unstake {
            sequencer_key,
            destination,
            amount,
            wallet_home,
        } => operator::unstake(wallet_home, sequencer_key, destination, amount).await,
    }
}

#[expect(
    clippy::integer_division_remainder_used,
    reason = "Generated by select! macro, can't be easily rewritten to avoid this lint"
)]
async fn start(
    home: &Path,
    rpc_address: SocketAddr,
    metrics_address: Option<SocketAddr>,
) -> Result<()> {
    let cancellation_token = listen_for_shutdown_signal();

    let config_path = home.join(operator::CONFIG_FILE);
    anyhow::ensure!(
        config_path.exists(),
        "{} has no config; run `setup` first",
        home.display()
    );
    let mut config = sequencer_service::SequencerConfig::from_path(&config_path)
        .with_context(|| format!("Failed to read {}", config_path.display()))?;
    anyhow::ensure!(
        home.join(sequencer_core::CHANNEL_SIGNING_KEY_FILE).exists(),
        "{} has no `{}`; run `setup` first",
        home.display(),
        sequencer_core::CHANNEL_SIGNING_KEY_FILE
    );
    sequencer_core::load_funding_public_key(home)?;
    config.home = home.to_path_buf();
    if metrics_address.is_some() {
        config.metrics_address = metrics_address;
    }

    if let Some(address) = config.metrics_address {
        install_prometheus_recorder(address)?;
    }
    let sequencer_handle = sequencer_service::run(config, rpc_address).await?;

    tokio::select! {
        () = cancellation_token.cancelled() => {
            log::info!("Shutting down sequencer...");
        }
        Err(err) = sequencer_handle.failed() => {
            error!("Sequencer failed unexpectedly: {err}");
        }
    }

    // Stop the watchers, the publisher's drive task, the block loop and the RPC
    // server, and wait for each. Dropping the handle only asks; the store stays
    // open for an unbounded stretch after that, so a restart can find its own
    // home directory locked, and a watcher can be killed between recording a
    // delivery and handing it over.
    sequencer_handle.shutdown().await;

    log::info!("Sequencer shutdown complete");

    Ok(())
}

/// Installs the recorder on `metrics_address`.
fn install_prometheus_recorder(metrics_address: SocketAddr) -> Result<()> {
    /// Ladder for `*_seconds` histograms, densest across the 1–100 ms band where
    /// block production and transaction application actually land.
    const LATENCY_BUCKETS: &[f64] = &[
        0.0005, 0.001, 0.0025, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0,
    ];

    /// Fallback ladder for histograms that count things rather than measure time.
    const COUNT_BUCKETS: &[f64] = &[1.0, 2.0, 5.0, 10.0, 25.0, 50.0, 100.0, 250.0, 500.0, 1000.0];

    PrometheusBuilder::new()
        .with_http_listener(metrics_address)
        .with_recommended_naming(true)
        .set_buckets(COUNT_BUCKETS)
        .context("Failed to set default histogram buckets")?
        .set_buckets_for_metric(Matcher::Suffix("_seconds".to_owned()), LATENCY_BUCKETS)
        .context("Failed to set latency histogram buckets")?
        .install()
        .context("Failed to install Prometheus recorder")
}

/// Cancelled on Ctrl-C or `SIGTERM`.
///
/// `SIGTERM` is what a container runtime sends first, so without it every
/// orchestrated stop is the ungraceful path.
#[expect(
    clippy::integer_division_remainder_used,
    reason = "Generated by select! macro, can't be easily rewritten to avoid this lint"
)]
fn listen_for_shutdown_signal() -> CancellationToken {
    let cancellation_token = CancellationToken::new();
    let cancellation_token_clone = cancellation_token.clone();

    tokio::spawn(async move {
        let mut terminate = match signal(SignalKind::terminate()) {
            Ok(terminate) => terminate,
            Err(err) => {
                error!("Failed to listen for SIGTERM: {err}");
                return;
            }
        };

        tokio::select! {
            result = tokio::signal::ctrl_c() => match result {
                Ok(()) => log::info!("Received Ctrl-C signal"),
                Err(err) => {
                    error!("Failed to listen for Ctrl-C signal: {err}");
                    return;
                }
            },
            _ = terminate.recv() => log::info!("Received SIGTERM"),
        }

        cancellation_token_clone.cancel();
    });

    cancellation_token
}
