use std::future::Future;

use common::{block::Block, transaction::LeeTransaction};
use futures::{StreamExt as _, TryFutureExt as _, TryStreamExt as _, future::ready, stream};
use kameo::{
    Actor,
    actor::{ActorRef, WeakActorRef},
    error::ActorStopReason,
    mailbox::{MailboxReceiver, Signal},
    message::{Context, Message},
    reply::DelegatedReply,
};
use lee_core::{
    BlockId,
    account::{Balance, Nonce},
};
use log::{info, warn};
use mempool::MemPoolHandle;
use sequencer_core::{
    PinBehindTip, SequencerCore, TransactionOrigin,
    block_publisher::{BlockPublisherTrait, MsgId},
    config::SequencerConfig,
    task_group::TaskGroup,
};
use sequencer_storage_actor::{StorageActor, StorageActorTrait};
use tokio::select;
use tokio_util::sync::CancellationToken;

use crate::{
    Result,
    error::Error,
    protocol::{
        GetAccount, GetAccountBalance, GetAccountNonces, GetAccountReply, GetBlock, GetBlockRange,
        GetChannelId, GetChannelIdReply, GetCrossZoneDeadLetters, GetCrossZoneDeadLettersReply,
        GetFeeQuote, GetFeeQuoteReply, GetLastBlockId, GetProofsAndRoot, GetTransaction,
        ProduceBlock, RequeueCrossZoneDeadLetter, RequeueCrossZoneDeadLetterReply, SubmitOutcome,
        Transaction,
    },
};

/// How many block lookups a single [`GetBlockRange`] keeps in flight.
const BLOCK_RANGE_CONCURRENCY: usize = 16;

/// Skips behind an unchanging tip past which this is a stuck pin, not catch-up.
const BLOCKED_ATTEMPTS_BEFORE_WEDGED: u32 = 4;

// TODO: Remove `BP` once this part is moved to a separate actor
pub struct ExecutorActor<BP: BlockPublisherTrait, S: StorageActorTrait = StorageActor> {
    mempool_handle: MemPoolHandle<(TransactionOrigin, LeeTransaction)>,
    sequencer: SequencerCore<BP, S>,
    storage_ref: ActorRef<S>,

    // --- TODO: Remove these fields below ---
    /// Cancelled when the publisher's drive task terminates (e.g. a panicked
    /// persist sink); no channel events are processed past that point.
    driver_cancellation: CancellationToken,
    /// The core's background tasks, taken before the core was shared. This
    /// handle owns no reference to the core itself, so without these there is
    /// nothing to wait on: aborting the main loop only starts the teardown.
    background_tasks: Vec<TaskGroup>,
    blocked_attempts: BlockedAttempts,
}

/// Consecutive production attempts skipped because the pin trailed the tip.
/// The run restarts on a new tip, so its length separates catching up from
/// being stuck.
#[derive(Default)]
pub(crate) struct BlockedAttempts {
    count: u32,
    behind: Option<MsgId>,
}

impl BlockedAttempts {
    /// Counts a skipped attempt and returns the run's new length.
    pub(crate) fn record(&mut self, tip: MsgId) -> u32 {
        if self.behind == Some(tip) {
            self.count = self.count.saturating_add(1);
        } else {
            self.behind = Some(tip);
            self.count = 1;
        }
        self.count
    }

    /// Ends the run, reporting whether there was one to end.
    pub(crate) fn clear(&mut self) -> bool {
        let blocked = self.behind.is_some();
        *self = Self::default();
        blocked
    }
}

impl<BP: BlockPublisherTrait + Send + 'static, S: StorageActorTrait> ExecutorActor<BP, S> {
    #[expect(
        clippy::manual_async_fn,
        reason = "Explicit Send future works around rust-lang/rust#100013"
    )]
    pub fn new(
        config: SequencerConfig,
        storage_ref: ActorRef<S>,
    ) -> impl Future<Output = Self> + Send + 'static {
        async move {
            // TODO: Leave storage_ref as a top-level field only in `ExecutorActor`,
            // while moving `SequencerCore` code into this actor.
            let (sequencer, mempool_handle) =
                SequencerCore::<BP, S>::start_from_config(config, storage_ref.clone()).await;

            let driver_cancellation = sequencer.block_publisher().driver_cancellation();
            let background_tasks = sequencer.background_tasks();

            Self {
                mempool_handle,
                sequencer,
                storage_ref,
                driver_cancellation,
                background_tasks,
                blocked_attempts: BlockedAttempts::default(),
            }
        }
    }

    /// Handle to the sequencer's mempool, for feeding externally-received
    /// (e.g. gossiped) transactions in.
    #[must_use]
    pub fn mempool_handle(&self) -> MemPoolHandle<(TransactionOrigin, LeeTransaction)> {
        self.mempool_handle.clone()
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait> Actor
    for ExecutorActor<BP, S>
{
    type Args = Self;
    type Error = Error;

    async fn on_start(args: Self::Args, _actor_ref: ActorRef<Self>) -> Result<Self> {
        Ok(args)
    }

    #[expect(
        clippy::integer_division_remainder_used,
        reason = "Generated by select! macro, can't be easily rewritten to avoid this lint"
    )]
    async fn next(
        &mut self,
        _actor_ref: WeakActorRef<Self>,
        mailbox_rx: &mut MailboxReceiver<Self>,
    ) -> Result<Option<Signal<Self>>> {
        // TODO: Remove this please
        for task in &self.background_tasks {
            if task.any_finished() {
                return Err(Error::BackgroundTaskFinishedUnexpectedly);
            }
        }

        select! {
            signal = mailbox_rx.recv() => {
                Ok(signal)
            }
            () = self.driver_cancellation.cancelled() => {
                Err(Error::BlockPublisherFinishedUnexpectedly)
            }
        }
    }

    async fn on_stop(
        &mut self,
        _actor_ref: WeakActorRef<Self>,
        _reason: ActorStopReason,
    ) -> Result<()> {
        for tasks in &self.background_tasks {
            tasks.shutdown().await;
        }

        Ok(())
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait> Message<ProduceBlock>
    for ExecutorActor<BP, S>
{
    type Reply = Result<()>;

    async fn handle(
        &mut self,
        ProduceBlock: ProduceBlock,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        // Only produce on our turn.
        if !self.sequencer.is_our_turn() {
            info!("Not our turn to produce a block, skipping");
            return Ok(());
        }

        // Never inscribe a second block at a height we already published: the
        // channel would carry two chains from there and nothing resolves that.
        if let Some(high_water) = self.sequencer.rewound_below_published().await {
            warn!(
                "Skipping turn: head rewound to {} but block {high_water} is already inscribed; \
                 waiting for the channel to restore it",
                self.sequencer.next_block_height().await.saturating_sub(1),
            );
            return Ok(());
        }

        // The channel moved past our pin, so every publish this turn would be refused.
        if let Some(PinBehindTip { pin, tip }) = self.sequencer.pin_behind_channel_tip().await {
            let attempts = self.blocked_attempts.record(tip);
            sequencer_core_metrics::record_publish_blocked_attempts(attempts);
            if attempts >= BLOCKED_ATTEMPTS_BEFORE_WEDGED {
                warn!(
                    "Skipped {attempts} production attempts behind an unchanging channel tip \
                     {tip}: our pin {pin} is frozen and cannot recover on its own. Land any \
                     inscription on the channel to trigger recovery, or reset the store.",
                );
            } else {
                info!(
                    "Skipping turn: channel tip {tip} moved past our pin {pin}; catching up first"
                );
            }
            return Ok(());
        }
        if self.blocked_attempts.clear() {
            sequencer_core_metrics::record_publish_blocked_attempts(0);
        }

        info!("Our turn: producing a block and any committee update");
        // A failed turn costs this block only. Returning the error would stop
        // this actor, and the scheduler's interval task gives up for good the
        // first time it finds us not running — the node then looks healthy and
        // never produces again.
        match self.sequencer.run_production_turn().await {
            Ok(id) => log::info!(
                "Block with id {id} created by {}",
                self.sequencer.bedrock_public_key_hex()
            ),
            Err(err) => warn!("Skipping turn: block production failed: {err:#}"),
        }

        Ok(())
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait> Message<Transaction>
    for ExecutorActor<BP, S>
{
    type Reply = Result<SubmitOutcome>;

    async fn handle(
        &mut self,
        Transaction { transaction }: Transaction,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        // Fee admission against the head state, before the mempool sees it.
        // Advisory (base fees and balances move), but everything it turns
        // away would have been refused by the block builder anyway.
        if let Err(rejection) = self
            .sequencer
            .with_state(|state| sequencer_core::fees::screen(&transaction, state))
            .await
        {
            return Ok(SubmitOutcome::Rejected(rejection));
        }

        self.mempool_handle
            .try_push((TransactionOrigin::User, transaction))
            .map_err(|_err| Error::MempoolIsFull)?;
        Ok(SubmitOutcome::Admitted)
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait> Message<GetBlock>
    for ExecutorActor<BP, S>
{
    type Reply = Result<Option<Block>>;

    async fn handle(
        &mut self,
        GetBlock { block_id }: GetBlock,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.storage_ref
            .ask(sequencer_storage_actor::protocol::GetBlock { block_id })
            .await
            .map_err(Into::into)
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait> Message<GetBlockRange>
    for ExecutorActor<BP, S>
{
    type Reply = DelegatedReply<Result<Vec<Block>>>;

    async fn handle(
        &mut self,
        GetBlockRange { range }: GetBlockRange,
        ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        let storage_ref = self.storage_ref.clone();

        ctx.spawn(async move {
            stream::iter(range.into_inner())
                .map(|block_id| {
                    storage_ref
                        .ask(sequencer_storage_actor::protocol::GetBlock { block_id })
                        .into_future()
                        .map_err(Into::into)
                })
                .buffered(BLOCK_RANGE_CONCURRENCY)
                .try_take_while(|block_opt| ready(Ok(block_opt.is_some())))
                .try_filter_map(|block_opt| ready(Ok(block_opt)))
                .try_collect()
                .await
        })
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait> Message<GetLastBlockId>
    for ExecutorActor<BP, S>
{
    type Reply = Result<BlockId>;

    async fn handle(
        &mut self,
        GetLastBlockId: GetLastBlockId,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        Ok(self.sequencer.chain_height().await)
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait>
    Message<GetAccountBalance> for ExecutorActor<BP, S>
{
    type Reply = Balance;

    async fn handle(
        &mut self,
        GetAccountBalance { account_id }: GetAccountBalance,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.sequencer
            .with_state(|state| state.get_account_by_id(account_id).balance)
            .await
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait> Message<GetFeeQuote>
    for ExecutorActor<BP, S>
{
    type Reply = GetFeeQuoteReply;

    async fn handle(
        &mut self,
        GetFeeQuote: GetFeeQuote,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        GetFeeQuoteReply {
            quote: self
                .sequencer
                .with_state(sequencer_core::fees::fee_quote)
                .await,
        }
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait> Message<GetTransaction>
    for ExecutorActor<BP, S>
{
    type Reply = Result<Option<(LeeTransaction, BlockId)>>;

    async fn handle(
        &mut self,
        GetTransaction { tx_hash }: GetTransaction,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.storage_ref
            .ask(sequencer_storage_actor::protocol::GetTransactionByHash { hash: tx_hash })
            .await
            .map_err(Into::into)
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait>
    Message<GetAccountNonces> for ExecutorActor<BP, S>
{
    type Reply = Vec<Nonce>;

    async fn handle(
        &mut self,
        GetAccountNonces { account_ids }: GetAccountNonces,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.sequencer
            .with_state(|state| {
                account_ids
                    .into_iter()
                    .map(|account_id| state.get_account_by_id(account_id).nonce)
                    .collect()
            })
            .await
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait>
    Message<GetProofsAndRoot> for ExecutorActor<BP, S>
{
    type Reply = (
        Vec<Option<lee_core::MembershipProof>>,
        lee_core::CommitmentSetDigest,
    );

    async fn handle(
        &mut self,
        GetProofsAndRoot { commitments }: GetProofsAndRoot,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        self.sequencer
            .with_state(|state| {
                let proofs = commitments
                    .iter()
                    .map(|commitment| state.get_proof_for_commitment(commitment))
                    .collect();
                (proofs, state.commitment_root())
            })
            .await
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait> Message<GetAccount>
    for ExecutorActor<BP, S>
{
    type Reply = GetAccountReply;

    async fn handle(
        &mut self,
        GetAccount { account_id }: GetAccount,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        GetAccountReply {
            account: self
                .sequencer
                .with_state(|state| state.get_account_by_id(account_id))
                .await,
        }
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait> Message<GetChannelId>
    for ExecutorActor<BP, S>
{
    type Reply = GetChannelIdReply;

    async fn handle(
        &mut self,
        GetChannelId: GetChannelId,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        GetChannelIdReply {
            channel_id: *self.sequencer.block_publisher().channel_id().as_ref(),
        }
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait>
    Message<GetCrossZoneDeadLetters> for ExecutorActor<BP, S>
{
    type Reply = Result<GetCrossZoneDeadLettersReply>;

    async fn handle(
        &mut self,
        GetCrossZoneDeadLetters: GetCrossZoneDeadLetters,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        let (total_retired, retained) = self
            .sequencer
            .cross_zone_dead_letters()
            .await
            .map_err(Error::CrossZoneDeadLettersUnavailable)?;
        Ok(GetCrossZoneDeadLettersReply {
            total_retired,
            retained: retained.into_iter().collect(),
        })
    }
}

impl<BP: BlockPublisherTrait + Send + Sync + 'static, S: StorageActorTrait>
    Message<RequeueCrossZoneDeadLetter> for ExecutorActor<BP, S>
{
    type Reply = Result<RequeueCrossZoneDeadLetterReply>;

    async fn handle(
        &mut self,
        RequeueCrossZoneDeadLetter { message_key }: RequeueCrossZoneDeadLetter,
        _ctx: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        let outcome = self
            .sequencer
            .requeue_cross_zone_dead_letter(message_key)
            .await
            .map_err(Error::CrossZoneDeadLetterRequeueFailed)?;
        Ok(RequeueCrossZoneDeadLetterReply { outcome })
    }
}
